[package]
name = "play-rust"
version = "0.1.0"
authors = ["GuoBin <guobin201314@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = "0.5.4"
